name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  PROJECT_ID: jiikko
  REGISTRY_HOST: asia-northeast1-docker.pkg.dev
  SERVICE_NAME: prpr-antena
  REPOSITORY_NAME: prpr-antena

jobs:
  create_deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: '${{ github.token }}'
          environment-url: https://pbm-cloud-dev.jiikko.com/
          environment: production
    outputs:
      deployment_id: ${{ steps.deployment.outputs.deployment_id }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"
      - name: "Use gcloud CLI"
        run: |
          gcloud auth list
          gcloud info
      - name: Authorize Docker push
        run: gcloud auth configure-docker "${REGISTRY_HOST}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          target: production
          tags: ${{ env.REGISTRY_HOST }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/web:master-${{ github.sha }} , ${{ env.REGISTRY_HOST }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/web:master
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
